#!/bin/bash

# install conky on debian based os with requirements
sudo apt install conky-all git fonts-font-awesome grep libx11-dev -y

CONKY_PATH=~/.config/conky
AUTOSTART="/etc/xdg/autostart"

# make config folder for user
mkdir -p $CONKY_PATH

# move necessary files 
cp conky.conf $CONKY_PATH
cp launchConky.sh $CONKY_PATH
cp onResolutionChange.sh $CONKY_PATH
cp *.lua $CONKY_PATH
echo "Configurations moved to $CONKY_PATH"

awk -v home="$HOME" '{ if ($0 ~ /Exec=.*/) {printf("Exec=%s/.config/conky/launchConky.sh\n", home)} else { print $0}}' conky.desktop >> conkyMod.desktop
sudo cp conkyMod.desktop "$AUTOSTART/conky.desktop"
rm conkyMod.desktop
echo "Added autostart entry at $AUTOSTART"

# make executable
sudo chmod +x "$CONKY_PATH/*.sh"

# git update submodules
git submodule update --init --recursive

# compile xeventbind and move to coky
cd xeventbind
make && cp xeventbind $CONKY_PATH
make clean

# start conky
bash ~/.config/conky/launchConky.sh
echo "Installation complete."

exit
