#!/bin/bash

# Kill processes
kill $( top -bn1 | grep "conky$" | awk '{print $1}' )
kill $( top -bn1 | grep "xeventbind$" | awk '{print $1}' )
echo "Killed conky processes."
# remove conky on debian based os
sudo apt remove conky conky-all -y

CONKY_PATH=~/.config/conky
AUTOSTART="/etc/xdg/autostart"

# remove conf files 
rm "$CONKY_PATH/conky.conf"
rm "$CONKY_PATH/launchConky.sh"
rm "$CONKY_PATH/onResolutionChange.sh"
echo "Configurations removed"

sudo rm "$AUTOSTART/conky.desktop"
echo "removed autostart entry from $AUTOSTART"

rm "$CONKY_PATH/xeventbind"

echo "Uninstallation complete."

exit
