#!/bin/bash

# Kill processes
kill $( top -bn1 | grep "conky$" | awk '{print $1}' )
kill $( top -bn1 | grep "xeventbind$" | awk '{print $1}' )

# remove conky on debian based os
CONKY=$( which conky )
if [ -f $CONKY ]; then
    sudo apt remove conky-all -y
fi

CONKY_PATH=~/.config/conky
AUTOSTART="/etc/xdg/autostart"

# remove conf files 
rm "$CONKY_PATH/conky.conf"
rm "$CONKY_PATH/launchConky.sh"
rm "$CONKY_PATH/onResolutionChange.sh"
echo "Configurations removed"

sudo rm "$AUTOSTART/conky.desktop"
echo "removed autostart entry from $AUTOSTART"

rm "$CONKY_PATH/xeventbind"

echo "Uninstallation complete."

exit
